# Generated by Django 3.0.2 on 2020-01-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponetwo',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
