# Generated by Django 3.0.2 on 2020-06-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='name',
            new_name='en',
        ),
        migrations.AddField(
            model_name='pathology',
            name='concept',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='is_general_of',
            field=models.ManyToManyField(related_name='_pathology_is_general_of_+', to='dictili_medical.Pathology'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictili_medical.Speciality'),
        ),
    ]
