# Generated by Django 3.0.2 on 2020-02-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0002_auto_20200131_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
