# Generated by Django 3.0.2 on 2020-07-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0002_auto_20200618_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='concept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='is_general_of',
            field=models.ManyToManyField(blank=True, related_name='_pathology_is_general_of_+', to='dictili_medical.Pathology'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictili_medical.Speciality'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='pathology',
            field=models.ManyToManyField(related_name='symptoms', to='dictili_medical.Pathology'),
        ),
    ]
