# Generated by Django 3.0.2 on 2020-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0003_auto_20200201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
    ]
