# Generated by Django 3.0.2 on 2020-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200611_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('P', 'Patient'), ('PRO', 'Professional')], default='P', max_length=4),
        ),
    ]
