# Generated by Django 3.0.2 on 2020-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='i_type',
            field=models.CharField(choices=[('B', 'Bistouri'), ('C', 'Cisors')], max_length=3, null=True),
        ),
    ]
