# Generated by Django 3.0.2 on 2020-06-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization_management', '0003_auto_20200630_1836'),
        ('healthcare_management', '0002_instrument_i_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcare',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='localization_management.State'),
        ),
    ]
