# Generated by Django 3.0.2 on 2020-06-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare_management', '0002_instrument_i_type'),
        ('dictili_medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('file_location', models.FileField(upload_to='generated\\audio')),
                ('concerns', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_management.Patient')),
                ('generated_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_management.HealthCareWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('contexts', models.ManyToManyField(related_name='_word_contexts_+', through='document_generation.ContextScore', to='document_generation.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('p', 'Prescription'), ('r', 'Report')], max_length=3)),
                ('text', models.CharField(max_length=2048)),
                ('text_file', models.FileField(upload_to='generated\\text\\reports')),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='document_generation.AudioFile')),
                ('words', models.ManyToManyField(to='document_generation.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contextscore',
            name='another_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_context', to='document_generation.Word'),
        ),
        migrations.AddField(
            model_name='contextscore',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contexts', to='dictili_medical.MedicalDomain'),
        ),
        migrations.AddField(
            model_name='contextscore',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_context', to='document_generation.Word'),
        ),
    ]
