# Generated by Django 3.0.2 on 2020-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text_file',
            field=models.FileField(upload_to='C:\\Users\\Simou\\Desktop\\PFE\\web_backend\\dictili\\uploads\\generated\\text\\reports'),
        ),
    ]
