# Generated by Django 3.0.2 on 2020-06-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictili_medical', '0001_initial'),
        ('document_generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='contextscore',
            unique_together={('word', 'another_word', 'domain')},
        ),
    ]
