# Generated by Django 3.0.2 on 2020-06-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_management', '0003_healthcare_state'),
        ('document_generation', '0002_auto_20200615_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='concerns',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_management.Patient'),
        ),
        migrations.AlterField(
            model_name='document',
            name='audio_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document_generation.AudioFile'),
        ),
    ]
