# Generated by Django 3.0.2 on 2020-07-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_management', '0003_healthcare_state'),
        ('document_generation', '0003_auto_20200630_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='concerns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_files', to='healthcare_management.Patient'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_files', to='healthcare_management.HealthCareWorker'),
        ),
    ]
