# Generated by Django 3.0.2 on 2020-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
