# Generated by Django 3.0.2 on 2020-06-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localization_management', '0002_auto_20200613_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
